# Example for integrating the SAJ H2 cards in Home Assistant

# 1. Copy files to the correct directories
# Create the following directory structure:
# /config/www/saj-h2-charge-card/
#   - saj-h2-charge-card-v3.js
#   - saj-h2-charge-card.css
# /config/www/saj-h2-discharge-card/
#   - saj-h2-discharge-card-v1.js
#   - saj-h2-discharge-card.css

# 2. Add resources in the Lovelace configuration
# Go to Settings -> Dashboards -> Resources

# For the charge card (ONLY the JS file):
# URL: /local/saj-h2-charge-card/saj-h2-charge-card-v3.js
# Resource Type: JavaScript Module

# For the discharge card (ONLY the JS file):
# URL: /local/saj-h2-discharge-card/saj-h2-discharge-card-v1.js
# Resource Type: JavaScript Module

# Note: The CSS files do NOT need to be added as resources.
# They are automatically loaded by the JavaScript files.

# 3. Add cards in a dashboard

# Example for the charge card (saj-h2-charge-card-v3):
type: 'custom:saj-h2-charge-card-v3'
charge_start_entity: text.saj_charge_start_time_time
charge_end_entity: text.saj_charge_end_time_time
charge_day_mask_entity: number.saj_charge_day_mask_input
charge_power_entity: number.saj_charge_power_percent_input
charging_switch_entity: switch.saj_charging_control

# Example for the discharge card (saj-h2-discharge-card-v1):
type: 'custom:saj-h2-discharge-card-v1'
# Optional: Configuration of entities, if they differ from the default values
time_enable_entity: number.saj_discharge_time_enable_input
discharging_switch_entity: switch.saj_discharging_control
# Optional: Configuration of time slots, if they differ from the default values
discharge_slots:
  - startTime: text.saj_discharge_start_time_time
    endTime: text.saj_discharge_end_time_time
    power: number.saj_discharge_power_percent_input
    dayMask: number.saj_discharge_day_mask_input
  - startTime: text.saj_discharge2_start_time_time
    endTime: text.saj_discharge2_end_time_time
    power: number.saj_discharge2_power_percent_input
    dayMask: number.saj_discharge2_day_mask_input
  - startTime: text.saj_discharge3_start_time_time
    endTime: text.saj_discharge3_end_time_time
    power: number.saj_discharge3_power_percent_input
    dayMask: number.saj_discharge3_day_mask_input
  - startTime: text.saj_discharge4_start_time_time
    endTime: text.saj_discharge4_end_time_time
    power: number.saj_discharge4_power_percent_input
    dayMask: number.saj_discharge4_day_mask_input
  - startTime: text.saj_discharge5_start_time_time
    endTime: text.saj_discharge5_end_time_time
    power: number.saj_discharge5_power_percent_input
    dayMask: number.saj_discharge5_day_mask_input
  - startTime: text.saj_discharge6_start_time_time
    endTime: text.saj_discharge6_end_time_time
    power: number.saj_discharge6_power_percent_input
    dayMask: number.saj_discharge6_day_mask_input
  - startTime: text.saj_discharge7_start_time_time
    endTime: text.saj_discharge7_end_time_time
    power: number.saj_discharge7_power_percent_input
    dayMask: number.saj_discharge7_day_mask_input

# Example for a complete dashboard with both cards
title: SAJ H2 Control
views:
  - title: Overview
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: '# SAJ H2 Inverter Control'
          - type: 'custom:saj-h2-charge-card-v3'
            charge_start_entity: text.saj_charge_start_time_time
            charge_end_entity: text.saj_charge_end_time_time
            charge_day_mask_entity: number.saj_charge_day_mask_input
            charge_power_entity: number.saj_charge_power_percent_input
            charging_switch_entity: switch.saj_charging_control
          - type: 'custom:saj-h2-discharge-card-v1'
            time_enable_entity: number.saj_discharge_time_enable_input
            discharging_switch_entity: switch.saj_discharging_control
