# Beispiel für die Einbindung der SAJ H2 Karten in Home Assistant

# 1. Dateien in die richtigen Verzeichnisse kopieren
# Erstelle folgende Verzeichnisstruktur:
# /config/www/saj-h2-charge-card/
#   - saj-h2-charge-card-v3.js
#   - saj-h2-charge-card.css
# /config/www/saj-h2-discharge-card/
#   - saj-h2-discharge-card-v1.js
#   - saj-h2-discharge-card.css

# 2. Ressourcen in der Lovelace-Konfiguration hinzufügen
# Gehe zu Einstellungen -> Dashboards -> Ressourcen

# Für die Ladekarte (NUR die JS-Datei):
# URL: /local/saj-h2-charge-card/saj-h2-charge-card-v3.js
# Ressourcentyp: JavaScript-Modul

# Für die Entladekarte (NUR die JS-Datei):
# URL: /local/saj-h2-discharge-card/saj-h2-discharge-card-v1.js
# Ressourcentyp: JavaScript-Modul

# Hinweis: Die CSS-Dateien müssen NICHT als Ressourcen hinzugefügt werden.
# Sie werden automatisch von den JavaScript-Dateien geladen.

# 3. Karten in einem Dashboard hinzufügen

# Beispiel für die Ladekarte (saj-h2-charge-card-v3):
type: 'custom:saj-h2-charge-card-v3'
charge_start_entity: text.saj_charge_start_time_time
charge_end_entity: text.saj_charge_end_time_time
charge_day_mask_entity: number.saj_charge_day_mask_input
charge_power_entity: number.saj_charge_power_percent_input
charging_switch_entity: switch.saj_charging_control

# Beispiel für die Entladekarte (saj-h2-discharge-card-v1):
type: 'custom:saj-h2-discharge-card-v1'
# Optional: Konfiguration der Entitäten, falls sie von den Standardwerten abweichen
time_enable_entity: number.saj_discharge_time_enable_input
discharging_switch_entity: switch.saj_discharging_control
# Optional: Konfiguration der Zeitslots, falls sie von den Standardwerten abweichen
discharge_slots:
  - startTime: text.saj_discharge_start_time_time
    endTime: text.saj_discharge_end_time_time
    power: number.saj_discharge_power_percent_input
    dayMask: number.saj_discharge_day_mask_input
  - startTime: text.saj_discharge2_start_time_time
    endTime: text.saj_discharge2_end_time_time
    power: number.saj_discharge2_power_percent_input
    dayMask: number.saj_discharge2_day_mask_input
  - startTime: text.saj_discharge3_start_time_time
    endTime: text.saj_discharge3_end_time_time
    power: number.saj_discharge3_power_percent_input
    dayMask: number.saj_discharge3_day_mask_input
  - startTime: text.saj_discharge4_start_time_time
    endTime: text.saj_discharge4_end_time_time
    power: number.saj_discharge4_power_percent_input
    dayMask: number.saj_discharge4_day_mask_input
  - startTime: text.saj_discharge5_start_time_time
    endTime: text.saj_discharge5_end_time_time
    power: number.saj_discharge5_power_percent_input
    dayMask: number.saj_discharge5_day_mask_input
  - startTime: text.saj_discharge6_start_time_time
    endTime: text.saj_discharge6_end_time_time
    power: number.saj_discharge6_power_percent_input
    dayMask: number.saj_discharge6_day_mask_input
  - startTime: text.saj_discharge7_start_time_time
    endTime: text.saj_discharge7_end_time_time
    power: number.saj_discharge7_power_percent_input
    dayMask: number.saj_discharge7_day_mask_input

# Beispiel für ein vollständiges Dashboard mit beiden Karten
title: SAJ H2 Steuerung
views:
  - title: Übersicht
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: '# SAJ H2 Wechselrichter Steuerung'
          - type: 'custom:saj-h2-charge-card-v3'
            charge_start_entity: text.saj_charge_start_time_time
            charge_end_entity: text.saj_charge_end_time_time
            charge_day_mask_entity: number.saj_charge_day_mask_input
            charge_power_entity: number.saj_charge_power_percent_input
            charging_switch_entity: switch.saj_charging_control
          - type: 'custom:saj-h2-discharge-card-v1'
            time_enable_entity: number.saj_discharge_time_enable_input
            discharging_switch_entity: switch.saj_discharging_control
